### ISSUE TITLE
[Feature] Hide Subquests from the list

### ISSUE THREAD

**Issue by Havoclivekiller** [typhonjs-fvtt/typhonjs-quest-log#102]
I personally liked how it looked before, where the subquests were hidden and you had to click on the main quest. Now I've got a lot of "clutter" in tabs due to the amount of subquest made. Can we get an option to hide them somehow?

**Comment by typhonrt** [comment]
Thanks for posting @Havoclivekiller. Indeed advanced sorting options are coming along with an intelligible way to show subquest relationships. The timing might be about ~2 months. I'm giving the RCOS team a bit of breathing room to work on their own enhancements for the next ~month then I'll be starting on a big update which will feature all sorts of advanced sorting and filtering of quests. 

So do be just a bit patient on this one. Indeed there is a bit more clutter, but there were downsides to the old way of only showing top level / parent quests. For instance if a parent quest is hidden or inactive and there is a subquest that is visible to players then there would be no way to navigate to that subquest. I do agree though that the current situation isn't going to be the end result. I expect this to be handled in the `0.8.0` release of FQL.

**Comment by typhonrt** [comment]
Hi folks.. I'm just streamlining the issues. While this issue is being closed Issue #103 tracks the enhancement mentioned here.
