### ISSUE TITLE
Provide a bundled and minified build

### ISSUE THREAD

**Issue by ghost91-** [typhonjs-fvtt/typhonjs-quest-log#143]
Currently, all the es modules are provided as separate files, which results in quite high load times for the module. In order to improve the situation, please provided a bundled and minified build.

Considering that FQL is in maintenance mode, I'm writing the issue here, but FQL of course also would benefit from this tremendously.

**Comment by typhonrt** [comment]
Closing now to clean issues up.. Indeed a bundle awaits..
