### ISSUE TITLE
[Feature Request] Objectives to have quantities (optional)

### ISSUE THREAD

**Issue by mnoreke** [typhonjs-fvtt/typhonjs-quest-log#155]
Objectives should have optional quantities, such as find 5 items. Tracked as 2/5 completed

**Comment by typhonrt** [comment]
This likely won't be implemented. If you need more granular control I suggest making a subquest for the item fetch portion of any larger quest. You can then break down the individual items in the subquest as discrete objectives. The subquest for the item fetch portion will have the "2 / 5" count in the objectives display then. 

In the continuation quest log there will be a significantly improved main quest log view that will group sub quests.
