### ISSUE TITLE
Quest Categories

### ISSUE THREAD

**Issue by mnoreke** [typhonjs-fvtt/typhonjs-quest-log#158]
When creating quests, it would be nice to organize them into categories to better keep track of them. This can be as an example either the area of the adventure, or perhaps factions of the quest giver.

**Comment by typhonrt** [comment]
This is already tracked by #103. Closing as duplicate. 

There will be expanded default options like "location" and others. It might be possible to have additional "top level" fields displayed on the main quest log view, but a feature that also covers "adhoc categories" is "user tagging" where tags can be entered and then the quest log view filtered / sorted by a number of options including user tags.
