### ISSUE TITLE
[Feature Request] quest dates and time based quest

### ISSUE THREAD

**Issue by SesuUisu** [typhonjs-fvtt/typhonjs-quest-log#159]
Having the possibility to track the time from when till when a quest was active.
This could also be used to trigger automatically a quest as active or finished/failed, when the deadline has arrived (I have no idea if that would be possible to be implemented in the quest log or in the time managing module like Simple Calendar).

**Comment by typhonrt** [comment]
Hi @SesuUisu. Thanks for writing up this enhancement. Indeed this is on the list already. I have marked this particular issue as a duplicate and have closed it. The idea in general is to support external integrations with Simple Calendar being a likely target for tracking time / calendar based operations.
