### ISSUE TITLE
[Feature Request] Player notes

### ISSUE THREAD

**Issue by ahrenm** [typhonjs-fvtt/typhonjs-quest-log#160]
The quest window is great. It would be awesome to allow player created notes against each quest. We just got pinged by our DM for not remembering the name of an NPC we we're asked to identify. Allowing player notes against the quests would mean that the data is all in once place.

**Comment by typhonrt** [comment]
Hi @ahrenm. Thanks for writing in an enhancement request. This is already being tracked by #150, so I'll mark this one as a duplicate. 

As far as timing goes. I'll be doing a crowdfunding effort to fund building a next-gen quest log likely starting around March '24. The general plan is to implement all 20+ enhancements being tracked here and bring a lot of UI / UX improvements to the quest log.
