### ISSUE TITLE
Readme Improvements

### ISSUE THREAD

**Issue by anthonyronda** [typhonjs-fvtt/typhonjs-quest-log#23]
Forien's Quest Log is a candidate for inclusion in the League's RCOS initiative, and this is an effort to beautify the project README to prepare for its introduction to students.

Suggestions:

- [ ] Add Screenshots/video
- [ ] Delete NOTE
- [ ] Delete Future Plans (reason: it appears to be 6 months out of date, and each of these should be issues/written under features)
- [ ] Add Contributing (include current translations section)
- [ ] Delete Patreon and Paypal links (this is a tough conversation and deserves input from the Patreon recipients, but the Patreon campaign appears to be stale. However links in the module.json should stay in perpetuity)

**Comment by typhonrt** [comment]
Closing... #144 tracks new documentation additions.
