### ISSUE TITLE
Update readme.md with some example of the new syntax

### ISSUE THREAD

**Issue by p4535992** [typhonjs-fvtt/typhonjs-quest-log#69]
Not a big deal, but if you could update the readme.md with some examples of the new syntax it would be greatly appreciated.
 
For example, before reading this reddit, I didn't know the syntax had changed.

https://www.reddit.com/r/FoundryVTT/comments/o9tlug/forien_quest_log_macro_popping_up_a_syntax_error/

**Comment by jinh5** [comment]
I would like to look into this one

**Comment by typhonrt** [comment]
Hi folks.. I'm just streamlining the issues. While this issue is being closed Issue #144 tracks the documentation enhancement mentioned here.
