### ISSUE TITLE
Reorder quests

### ISSUE THREAD

**Issue by droza888** [typhonjs-fvtt/typhonjs-quest-log#7]
I would love it if it were possible to reorder the quests somehow. My players would like to order them according to their priority for them, the order they intend to do them, or similar.

**Comment by adacosta92** [comment]
To add to this, the ability to reorder subquests within quests just like reordering objectives

**Comment by typhonrt** [comment]
Hi folks.. I'm just streamlining the issues. While this issue is being closed Issue #103 tracks the enhancement mentioned here.
